### ISSUE TITLE
Checksum mismatch on Windows

### ISSUE THREAD

**Issue by EricForgy** [JuliaOpt/ECOS.jl#23]
julia> versioninfo()
Julia Version 0.3.10
Commit c8ceeef* (2015-06-24 13:54 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: AMD Opteron(tm) Processor 4171 HE
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Barcelona)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

-------------------------------------------

Hi,

Any ideas?

julia> Pkg.rm("ECOS")
INFO: Removing ECOS v0.4.2
INFO: Package database updated

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> Pkg.add("ECOS")
INFO: Installing ECOS v0.4.2
INFO: Building ECOS
INFO: Attempting to Create directory C:\Users\Eric.Forgy\.julia\v0.3\ECOS\deps\d
ownloads
INFO: Directory C:\Users\Eric.Forgy\.julia\v0.3\ECOS\deps\downloads already crea
ted
INFO: Downloading file https://cache.e.ip.saba.us/http://sourceforge.net/project
s/juliadeps-win/files/ecos-e05a605588c38ad72e843f36af17f8f84e4e2ccb.7z
INFO: Done downloading file https://cache.e.ip.saba.us/http://sourceforge.net/pr
ojects/juliadeps-win/files/ecos-e05a605588c38ad72e843f36af17f8f84e4e2ccb.7z
================================[ ERROR: ECOS ]=================================

Checksum mismatch!  Expected:
add47e8b2b14a67c5681a5a77a4dafe0bc4d5efacb38f8c7dffafea79d49d89d
Calculated:
818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821
Delete C:\Users\Eric.Forgy\.julia\v0.3\ECOS\deps\downloads\ecos-e05a605588c38ad7
2e843f36af17f8f84e4e2ccb.7z and try again
while loading C:\Users\Eric.Forgy\.julia\v0.3\ECOS\deps\build.jl, in expression
starting on line 49

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: ECOS had build errors.

 - packages with build errors remain installed in C:\Users\Eric.Forgy\.julia\v0.
3
 - build the package(s) and all dependencies with `Pkg.build("ECOS")`
 - build a single package by running its `deps/build.jl` script

================================================================================

INFO: Package database updated

-----------------------------------

It says, "Delete C:\Users\Eric.Forgy\.julia\v0.3\ECOS\deps\downloads\ecos-e05a605588c38ad7
2e843f36af17f8f84e4e2ccb.7z and try again" so I try it, but when I Pkg.build() again, I get the same error.

PS: If it matters, this is a virtual machine running on Azure.

Thanks for any help.

**Comment by mlubin** [comment]
Also seems to happen with scs. @staticfloat, should we just update to the new hashes?

**Comment by staticfloat** [comment]
Well something is very odd, because when I download the file myself, I get the right SHA sum:

```
$ curl -L https://cache.e.ip.saba.us/http://sourceforge.net/projects/juliadeps-win/files/ecos-e05a605588c38ad72e843f36af17f8f84e4e2ccb.7z | shasum -a 256
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  164k  100  164k    0     0  35592      0  0:00:04  0:00:04 --:--:--  367k
add47e8b2b14a67c5681a5a77a4dafe0bc4d5efacb38f8c7dffafea79d49d89d  -
```

Aha, actually, I know what happened.  Sourceforge had some recent downtime, and rather than give out HTTP 404 error codes like a sane hosting provider would during downtime, they returned HTTP 200 OK, thereby making the cache server think that something had indeed changed.  So the caching server took the error page, saved it as a new version of ECOS, and started serving it out until the actual version came back.

Needless to say, there's something to fix in that behavior, however the file has reverted itself now that Sourceforge is back up, and everything should be working as intended now.

**Comment by EricForgy** [comment]
Hehe :)

That is my luck. Thank you for the explanation. I was able to install it just now.

**Comment by tkelman** [comment]
alright that does it I'm taking my own medicine and moving everything to bintray
