### ISSUE TITLE
Support for exponential cones

### ISSUE THREAD

**Issue by madeleineudell** [JuliaOpt/ECOS.jl#24]
The [new ECOS API](https://www.embotech.com/ECOS/How-to-use/C-API) adds support for exponential cones, introducing breaking changes with the old API. In this repo, we'll need to update the ECOS.jl interface to accept exponential cones from the MathProgBase conic form and should to modify the data structures here to reflect the new C API.

**Comment by mlubin** [comment]
Looking forward to trying this out.
