### ISSUE TITLE
incorrect dual solution

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/ECOS.jl#26]
```
using MathProgBase
using ECOS
solver = ECOSSolver()
# min  x
# s.t. y ≥ 1
#      x² + y² ≤ 1
# in conic form:
# min  x
# s.t.  -1 + y ∈ R₊
#        1 - t ∈ {0}
#      (t,x,y) ∈ SOC₃

b = [-1, 1, 0, 0, 0]
A = [ 0 -1 0
      0 0 1
      0 0 -1
      -1 0 0
      0 -1 0 ]
c = [ 1, 0, 0 ]
constr_cones = [(:NonNeg,1:1),(:Zero,2:2),(:SOC,3:5)]
var_cones = [(:Free,1:3)]

m = MathProgBase.model(solver)
MathProgBase.loadconicproblem!(m, c, A, b, constr_cones, var_cones)
MathProgBase.optimize!(m)
@show MathProgBase.status(m)
@show MathProgBase.getobjval(m)
@show MathProgBase.getsolution(m)
y = MathProgBase.getconicdual(m)
@show y
@show -dot(b,y) # should match primal objective
@show c + A'y # should be all zeros, since variables are free
```
gives
```
MathProgBase.status(m) => :Optimal
MathProgBase.getobjval(m) => -0.00012202859247851328
MathProgBase.getsolution(m) => [-0.00012202859247851328,1.000000000996518,1.0000000000204559]
y => [5676.161928384324,-5676.162023291244,-5676.162023295641,-0.9999999999997287,5676.161928372228]
-(dot(b,y)) => 11352.323951675568
c + A' * y => [1.9999999999997287,-11352.323856756553,4.397406883072108e-9]
```
The dual objective doesn't match the primal, and dual feasibility isn't satisfied, according to the [MPB primal/dual pair](http://mathprogbasejl.readthedocs.org/en/latest/conic.html).
CC @IainNZ @kaarthiksundar

**Comment by IainNZ** [comment]
Out of curiousity, if you do y>=0.9 are the duals less crazy?

**Comment by mlubin** [comment]
Less crazy but still not dual feasible:
```
MathProgBase.getobjval(m) => -0.4358898994894706
-(dot(b,y)) => 4.152783227167962
c + A' * y => [1.9999999999999991,-4.129881478654459,1.4893344335575875e-9]
```

**Comment by mlubin** [comment]
We can relax the test to ``y >= 0.9`` if that's more fair.

**Comment by IainNZ** [comment]
I mean I'm just not sure if the dual is well-defined at `y >= 1.0`, but it should be OK for `y >= 0.9`

**Comment by mlubin** [comment]
Interestingly with y >= 0.9, SCS seems to settle on the same solution:
```
MathProgBase.status(m) => :Optimal
MathProgBase.getobjval(m) => -0.4358911334118897
MathProgBase.getsolution(m) => [-0.4358911334118897,0.900002647479489,1.0000024838844805]
y => [2.0647457806859504,-2.294163391791631,-2.294164302057801,-1.000002879308829,2.064747947380117]
-(dot(b,y)) => 4.152434594408986
c + A' * y => [2.0000028793088287,-4.129493728066068,9.102661699955661e-7]
```
Ref https://github.com/JuliaOpt/SCS.jl/issues/40

**Comment by IainNZ** [comment]
Duality is a trip

**Comment by IainNZ** [comment]
I mean, doesn't MOSEK modeling manual say its possible to get a bound gap?

**Comment by IainNZ** [comment]
http://docs.mosek.com/generic/modeling-letter.pdf `3.4.2 Examples of bad duality states`

**Comment by mlubin** [comment]
There's a negative gap here though, the dual objective is greater than the primal.

**Comment by IainNZ** [comment]
Why do you have the negative sign there?

**Comment by mlubin** [comment]
That's the definition of our primal/dual pair in MPB.

**Comment by IainNZ** [comment]
So what do we think is the dual of this problem?

**Comment by mlubin** [comment]
```
max -b^Ty
s.t. c + A^Ty = 0
      y in R_+ cross {0} cross SOC_3
```
with A,b,c defined above.

**Comment by mlubin** [comment]
The solution vector ``y`` returned by ECOS satisfies the cone conditions (``R_+ cross R cross SOC_3``) but not ``c + A^Ty = 0``.

**Comment by kaarthiksundar** [comment]
Okay, I am having an issue with the dual. The following problem 

    using MathProgBase
    using Mosek 
    using ECOS

    # min  x
    # s.t. y ≥ 0.9
    #      x² + y² ≤ 1 
    # in conic form:
    # min  x
    # s.t.  0.9 - y ∈ R₋
    #        1 - t ∈ {0}
    #      (t,x,y) ∈ SOC₃

    b = [-1, 0.9, 0, 0, 0]
    A = [ 0 1 0
          0 0 1
          0 0 -1
         -1 0 0
         0 -1 0 ]
     c = [ 1, 0, 0 ]
     constr_cones = [(:NonPos,1:1),(:Zero,2:2),(:SOC,3:5)]
     var_cones = [(:Free,1:3)]
     m = MathProgBase.model(ECOSSolver()) 
    MathProgBase.loadconicproblem!(m, c, A, b, constr_cones, var_cones)
    MathProgBase.optimize!(m)
    @show MathProgBase.status(m) 
    @show MathProgBase.getobjval(m)
    @show MathProgBase.getsolution(m)
     y = MathProgBase.getconicdual(m)
    @show y
    @show dot(b,y)
    @show c - A'y

gives 
```
 ECOS 1.0.5 - (c) A. Domahidi, ETH Zurich & embotech 2012-14. Support: ecos@embotech.com

It     pcost         dcost      gap     pres    dres     k/t     mu      step     IR
 0   +0.000e+00   -3.749e+00   +2e+00   1e-02   2e+00   1e+00   9e-01    N/A     2 3 -
 1   -2.743e-01   -1.900e+00   +7e-01   7e-03   1e+00   6e-01   4e-01   0.6491   4 3 4
 2   -5.177e-01   -8.820e-01   +1e-01   2e-03   3e-01   2e-01   8e-02   0.7954   3 3 3
 3   -8.444e-01   -1.138e+00   +9e-02   2e-03   3e-01   3e-01   5e-02   0.6552   2 2 2
 4   -8.722e-01   -9.079e-01   +1e-02   2e-04   3e-02   2e-02   4e-03   0.9107   3 3 3
 5   -8.988e-01   -9.049e-01   +2e-03   2e-05   4e-03   2e-03   7e-04   0.9029   2 2 2
 6   -8.995e-01   -9.002e-01   +2e-04   3e-06   4e-04   2e-04   8e-05   0.8876   2 2 2
 7   -9.000e-01   -9.001e-01   +3e-05   5e-07   9e-05   6e-05   2e-05   0.9273   2 2 2
 8   -9.000e-01   -9.000e-01   +4e-06   7e-08   1e-05   8e-06   2e-06   0.8773   2 2 2
 9   -9.000e-01   -9.000e-01   +7e-07   1e-08   2e-06   2e-06   4e-07   0.9218   2 2 2
10   -9.000e-01   -9.000e-01   +1e-07   2e-09   3e-07   2e-07   5e-08   0.8636   3 2 2
11   -9.000e-01   -9.000e-01   +2e-08   3e-10   6e-08   5e-08   1e-08   0.9062   3 2 2

OPTIMAL (within feastol=5.6e-08, reltol=2.3e-08, abstol=2.1e-08).
Runtime: 0.000315 seconds.

MathProgBase.status(m) => :Optimal
MathProgBase.getobjval(m) => -0.8999999819804814
MathProgBase.getsolution(m) => [-0.8999999819804814,0.00016486322497752756,0.8999999999999999]
y => [-4.8998726203559844e-8,-1.0000000016344572,-1.0000000348808287,-0.9999999999999997,-4.240772223596713e-8]
dot(b,y) => -0.8999999524722854
c - A' * y => [3.3306690738754696e-16,6.591003967592715e-9,-3.324637143364839e-8]
```

which seems to be right. In the definition of the primal dual pair, i think the correct dual values are -y instead of y. Only then will things work out as they should. The same behaviour is observed in MOSEK also.

**Comment by mlubin** [comment]
```
using MathProgBase
using ECOS
solver = ECOSSolver()
# min  x
# s.t. y ≥ 1
#      x² + y² ≤ 1
# in conic form:
# min  x
# s.t.  -1 + y ∈ R₊
#        1 - t ∈ {0}
#      (t,x,y) ∈ SOC₃

b = [-0.9, 1, 0, 0, 0]
A = [ 0 -1 0
      0 0 1
      0 0 -1
      -1 0 0
      0 -1 0 ]
c = [ 1, 0, 0 ]
constr_cones = [(:NonNeg,1:1),(:Zero,2:2),(:SOC,3:5)]
var_cones = [(:Free,1:3)]

m = MathProgBase.model(solver)
MathProgBase.loadconicproblem!(m, c, A, b, constr_cones, var_cones)
MathProgBase.optimize!(m)
@show MathProgBase.status(m)
@show MathProgBase.getobjval(m)
@show MathProgBase.getsolution(m)
y = MathProgBase.getconicdual(m)
@show y
@show -dot(b,y) # should match primal objective
@show c + A'y # should be all zeros, since variables are free
y = -y
y[1] *= -1
@show -dot(b,y) # should match primal objective
@show c + A'y # should be all zeros, since variables are free
```
gives
```
MathProgBase.status(m) => :Optimal
MathProgBase.getobjval(m) => -0.4358898994894706
MathProgBase.getsolution(m) => [-0.4358898994894706,0.9000000007747969,0.9999999999999976]
y => [2.0649407413745924,-2.2943365599308287,-2.294336561420163,-0.9999999999999992,2.0649407372798665]
-(dot(b,y)) => 4.152783227167962
c + A' * y => [1.9999999999999991,-4.129881478654459,1.4893344335575875e-9]
-(dot(b,y)) => -0.4358898926936956
c + A' * y => [7.771561172376096e-16,-4.094725891690132e-9,-1.4893344335575875e-9]
```
So we get a good answer if we negate y except for the first component.

**Comment by kaarthiksundar** [comment]
I don't get what you did. I did not negate the first component. Yet, I got the correct solution.

**Comment by mlubin** [comment]
``:NonPos`` vs ``:NonNeg``

**Comment by kaarthiksundar** [comment]
This is all the more confusing. All solvers (SCS, ECOS, Mosek) behave the same way. Are we missing something?

**Comment by mlubin** [comment]
There are a bunch of tests for duals [here](https://github.com/JuliaOpt/MathProgBase.jl/blob/master/test/conicinterface.jl). I wonder if they're actually correct. Either that or there's something wrong with the primal-dual pair in the MPB docs.

**Comment by mlubin** [comment]
(Testing for the wrong solution is a good way to make all solvers behave the same way.)

**Comment by kaarthiksundar** [comment]
I don't see any tests that actually check if the primal and dual solutions match when the constraint qualification conditions are satisfied. I will look at the dual solution for some of the tests to narrow down the issue.

**Comment by mlubin** [comment]
What about here:
https://github.com/JuliaOpt/MathProgBase.jl/blob/master/test/conicinterface.jl#L38
https://github.com/JuliaOpt/MathProgBase.jl/blob/master/test/conicinterface.jl#L176
https://github.com/JuliaOpt/MathProgBase.jl/blob/master/test/conicinterface.jl#L205

**Comment by mlubin** [comment]
I just looked at [problem 3A](https://github.com/JuliaOpt/MathProgBase.jl/blob/defdd7a373017af1a5e3b37312adc426821b9c05/test/conicinterface.jl#L180) and the test is checking for the wrong sign. The sign needs to be flipped to satisfy dual feasibility according to our definition.

**Comment by kaarthiksundar** [comment]
Our definition meaning, the MBP primal dual pair?

Regards
Kaarthik

**Comment by mlubin** [comment]
yes

**Comment by mlubin** [comment]
For example, https://github.com/JuliaOpt/MathProgBase.jl/blob/defdd7a373017af1a5e3b37312adc426821b9c05/test/conicinterface.jl#L206
(d[2],d[3],d[3]) should belong to the second order cone, but we're checking that the first component is negative, which doesn't make any sense.
