### ISSUE TITLE
getdual for exp cone problem seems to be failing

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/ECOS.jl#39]
For the second ExpPrimal constraint cone, the dual subvector is not in the ExpDual cone:
```
c = [0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0]
b = [0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0]

I = [8,11,1,4,9,12,1,4,10,13,3,7,6,7,7,8,11,14,15,9,12,14,10,13,14]
J = [1,1,2,2,2,2,3,3,3,3,4,4,5,5,6,7,7,7,7,8,8,8,9,9,9]
V = [-1.0,1.0,-1.0,-1.0,-1.0,1.0,-1.0,1.0,-1.0,1.0,-1.0,-0.5,-1.0,-0.5,1.0,-0.3,-0.3,1.0,-1.0,-0.3,-0.3,1.0,-0.3,-0.3,1.0]
A = sparse(I, J, V, length(b), length(c))

cone_con = [(:ExpPrimal,1:3),(:ExpPrimal,4:6),(:Zero,7:7),(:NonNeg,8:10),(:NonNeg,11:13),(:NonNeg,14:14),(:Zero,15:15)]
cone_var = [(:Free,1:9)]

using Pajarito, MathProgBase
using Gurobi
using ECOS, SCS

const conic_solver = SCSSolver()

# const conic_solver = ECOSSolver(
#     verbose = 1,
#     )

m = MathProgBase.ConicModel(conic_solver)
MathProgBase.loadproblem!(m, c, A, b, cone_con, cone_var)
MathProgBase.optimize!(m)

@show MathProgBase.getobjval(m)
@show MathProgBase.getsolution(m)
@show MathProgBase.getdual(m)
```

Using ECOS:
```
MathProgBase.getobjval(m) = 0.7408182208915618
MathProgBase.getsolution(m) = [0.0,-0.2999999992457157,-1.1007103463833066e-18,0.7408182208782725,0.7408182208567478,0.7408182208915618,4.3517990681358206e-12,0.9999999979627452,1.015033875874738e-9]
MathProgBase.getdual(m) = [-0.3704091105217561,-0.48153184346656197,0.5000000000253126,0.5000000000253126,-0.3704091105111865,-0.48153184346656197,-0.9999999996995307,0.731888925050261,0.7408182209209416,0.37040911060278864,0.731888925050261,1.8935064499404854e-10,0.370409110592219,0.2222454664706639,-0.21688788867220815]
```
`0.5000000000253126,-0.3704091105111865,-0.48153184346656197` is not in ExpDual (u > 0)

Using SCS:
```
MathProgBase.getobjval(m) = 0.74082536604892
MathProgBase.getsolution(m) = [0.0,-0.2999913827692533,0.0,0.7408253577976333,0.7408253577976333,0.74082536604892,1.2909207042113865e-6,0.9999851093522414,9.108218830772213e-6]
MathProgBase.getdual(m) = [-0.37044072381433724,-0.48156771648171787,0.5000356214691597,-0.37044072381433724,-0.48156771648171787,0.5000356214691597,-1.000000001250412,0.11069912783749614,0.7410052409028142,0.3705209764950191,0.11069912783749614,0.0,0.3705209764950191,0.2223125848118538,0.15589310857170166]
```
`(-0.37044072381433724,-0.48156771648171787,0.5000356214691597)` is in ExpDual

The primal solutions for ECOS and SCS match. But it appears that some of the dual subvectors for constraint cones have been "reversed" in the dual returned by ECOS.

**Comment by mlubin** [comment]
That's weird, I wonder why [this test](https://github.com/JuliaOpt/MathProgBase.jl/blob/fe17d4df5980b165224829bd9b2ff513683d5ee1/test/conicinterface.jl#L391) passes.

**Comment by chriscoey** [comment]
because it's too simple
the dual for the first ExpPrimal in the example I have works. just not the second ExpPrimal.

**Comment by mlubin** [comment]
There's a permutation of indices for the exponential cone [here](https://github.com/JuliaOpt/ECOS.jl/blob/6bdc96e051ec65a94a0eda29c78d0c6165f22cfb/src/ECOSSolverInterface.jl#L353). There might be a bug in the logic or we may need to do another permutation [here](https://github.com/JuliaOpt/ECOS.jl/blob/6bdc96e051ec65a94a0eda29c78d0c6165f22cfb/src/ECOSSolverInterface.jl#L383).

**Comment by chriscoey** [comment]
who wrote it?

**Comment by mlubin** [comment]
Moi: https://github.com/JuliaOpt/ECOS.jl/blame/6bdc96e051ec65a94a0eda29c78d0c6165f22cfb/src/ECOSSolverInterface.jl#L383

**Comment by IainNZ** [comment]
I think I wrote it wrong first though ;)

**Comment by chriscoey** [comment]
i'm not seeing the problem, but i don't really understand how ECOS takes in inputs

**Comment by mlubin** [comment]
The exact format is described here: https://www.embotech.com/ECOS/How-to-use/C-API
