### ISSUE TITLE
Is it dangerous to use `unsafe_wrap` to pull solver solution?

### ISSUE THREAD

**Issue by mpf** [JuliaOpt/ECOS.jl#95]
The `MOI.optimize!` function extracts the solution variables from the ECOS problem structure using `unsafe_wrap`, eg, on [this line](https://github.com/JuliaOpt/ECOS.jl/blob/c59788be8a89922f5a420858042b1329b84451a8/src/MOI_wrapper.jl#L269),

    primal = unsafe_wrap(Array, ecos_prob.x, n)[:]

Perhaps I misunderstand the implications of `unsafe_wrap`, but couldn't the subsequent call to `cleanup`, which calls `free` on the corresponding memory location, cause a problem?

**Comment by mlubin** [comment]
Unless Julia changed recently, the `[:]` at the end should make a
julia-managed copy of the array created by `unsafe_wrap`.

**Comment by mpf** [comment]
Thanks for explaining, @mlubin! Yes, that makes sense.
